paths:
  yolo_model: "/scratch/soumo_roy/baseline-scripts/weights/yolov8l.pt"
  sam_checkpoint: "/scratch/soumo_roy/baseline-scripts/weights/sam_hq_vit_l.pth"

models:
  sam_model_type: "vit_l"
  device: "cuda:0"

sahi_params:
  slice_height: 512
  slice_width: 512
  overlap_ratio: 0.2

detection_params:
  confidence_threshold: 0.3
  nms_threshold: 0.5

tracking_params:
  movement_threshold_pixels: 5
  static_frame_count_threshold: 3
  movement_threshold_meters: 0.1  
  velocity_threshold: 0.03 # meters per second

calibration:
  extrinsics:
    translation: [0.002065, -0.172389, 0.069317]  # x, y, z in meters
    rotation: [-0.500030, 0.503525, -0.501838, 0.494558] # quaternion (qx, qy, qz, qw)

  intrinsics:
    width: 1920
    height: 960
    fx: 960.0
    fy: 960.0
    cx: 960.0
    cy: 480.0
    distortion: [-0.40817, 0.18282, 0.01766, -0.02024]

dbscan_params:
  eps: 0.15 # the distance here is in meters
  min_samples: 5 # min number points for cluster

models_deployemnt:
  # YOLOv8 ONNX engine path
  yolo_onnx_path: "weights/yolov8l.onnx" # Change if you generated a .engine file
  
  # SAM ONNX engine paths (encoder and decoder)
  sam_encoder_onnx_path: "weights/sam_l_encoder.onnx" # Change if you generated .engine files
  sam_decoder_onnx_path: "weights/sam_l_decoder.onnx"

  # Inference provider (for ONNX Runtime)
  # 'CUDAExecutionProvider' for GPU, 'CPUExecutionProvider' for CPU
  # 'TensorrtExecutionProvider' if you exported to TensorRT and use ORT for inference
  onnx_provider: "CUDAExecutionProvider" # Or "TensorrtExecutionProvider" if using TRT engines