defaults:
  - _self_

system:
  device: "cuda:0"
  num_workers: 5
  output_dir: "./MCMPT_output"
  verbose: false

models:
  detection:
    path: "/scratch/soumo_roy/baseline-scripts/weights/yolo11l.pt" # yolo path

    # CONFIDENCE THRESHOLD (Crucial for ByteTrack)
    # We keep this LOW (0.25) to allow ByteTrack to track occluded people.
    conf_threshold: 0.25
    classes: [0]

  sahi:
    slice_height: 512
    slice_width: 512
    overlap_ratio: 0.2
    verbose: 0

  pose:
    type: "human"

  segmentation:
    path: "/scratch/soumo_roy/baseline-scripts/weights/sam2.1_l.pt" # sam2 path
    run_every_n_frames: 1

  reid:
    name: "osnet_x1_0"
    match_threshold: 0.75 # # 0.75 = Strict (Less false positives, but might lose ID if person turns 180 deg)
    path: "/scratch/soumo_roy/baseline-scripts/weights/osnet_x0_25_msmt17.pt"

tracker:
  type: "botsort.yaml"
  gmc_method: "sparseOptFlow"
  with_reid: True

  # for the mall data
  track_high_thresh: 0.5  # High confidence threshold
  track_low_thresh: 0.1   # Low confidence threshold (picks up occluded people)
  new_track_thresh: 0.6   # Confidence required to start a NEW track ID
  track_buffer: 60        # Retain lost tracks for 60 frames (2 seconds) to handle pillars/obstructions
  match_thresh: 0.8       # IoU threshold for matching boxes

analysis:
  movement:
    history_len: 10
    threshold: 0.03 # 0.02 means the ankles must move 2% of the body height to be considered "Moving"
    cooldown_frames: 5

cameras:
  - id: 1
    path: "/scratch/soumo_roy/baseline-scripts/rosbag_processing_script/data_extraction/camera1"
  - id: 2
    path: "/scratch/soumo_roy/baseline-scripts/rosbag_processing_script/data_extraction/camera2"
  - id: 3
    path: "/scratch/soumo_roy/baseline-scripts/rosbag_processing_script/data_extraction/camera3"
  - id: 4
    path: "/scratch/soumo_roy/baseline-scripts/rosbag_processing_script/data_extraction/camera4"
  - id: 5
    path: "/scratch/soumo_roy/baseline-scripts/rosbag_processing_script/data_extraction/camera5"