topics:
  - name: /tf
    type: tf2_msgs/msg/TFMessage
    count: 3838
    serialization_format: cdr
  - name: /livox/lidar
    type: sensor_msgs/msg/PointCloud2
    count: 3844
    serialization_format: cdr
  - name: /livox/imu
    type: sensor_msgs/msg/Imu
    count: 76885
    serialization_format: cdr
  - name: /camera1/camera1/color/image_raw
    type: sensor_msgs/msg/Image
    count: 11477
    serialization_format: cdr
  - name: /joy_teleop/cmd_vel
    type: geometry_msgs/msg/Twist
    count: 22869
    serialization_format: cdr
  - name: /husky_velocity_controller/odom
    type: nav_msgs/msg/Odometry
    count: 3839
    serialization_format: cdr
  - name: /dual_fisheye/image/compressed
    type: sensor_msgs/msg/CompressedImage
    count: 11502
    serialization_format: cdr
  - name: /camera4/camera4/color/camera_info
    type: sensor_msgs/msg/CameraInfo
    count: 11527
    serialization_format: cdr
  - name: /tf_static
    type: tf2_msgs/msg/TFMessage
    count: 6
    serialization_format: cdr
  - name: /camera5/camera5/color/image_raw
    type: sensor_msgs/msg/Image
    count: 11385
    serialization_format: cdr
  - name: /camera3/camera3/color/camera_info
    type: sensor_msgs/msg/CameraInfo
    count: 11527
    serialization_format: cdr
  - name: /camera4/camera4/color/image_raw
    type: sensor_msgs/msg/Image
    count: 11411
    serialization_format: cdr
  - name: /camera2/camera2/color/image_raw
    type: sensor_msgs/msg/Image
    count: 11369
    serialization_format: cdr
  - name: /equirectangular/image
    type: sensor_msgs/msg/Image
    count: 11499
    serialization_format: cdr
  - name: /camera5/camera5/color/camera_info
    type: sensor_msgs/msg/CameraInfo
    count: 11508
    serialization_format: cdr
  - name: /camera3/camera3/color/image_raw
    type: sensor_msgs/msg/Image
    count: 11442
    serialization_format: cdr